### ISSUE TITLE
Doesn't work when running outside of Docker

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/sdx-console#13]
The README says that the console can be run outside of Docker, but this doesn't work as there are dependencies missing from requirements.txt (provided by the onsdigital/flask-crypto-queue Docker image). There are also some undocumented mandatory environment variables. Should this app work outside of Docker?

**Comment by iwootten** [comment]
It previously did, it no longer does - given the readme is now updated to this effect I'm closing this.
